repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0 # Use the latest version
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_tfsec